# Generated by Django 6.0.1 on 2026-01-19 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheaterPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('suspect_username', models.CharField(max_length=255)),
                ('game_name', models.CharField(max_length=255)),
                ('youtube_url', models.URLField()),
                ('suspected_hack_types', models.JSONField(choices=[('aimbot', 'Aimbot'), ('esp', 'ESP'), ('wallhack', 'Wallhack'), ('speedhack', 'Speed Hack'), ('noclip', 'No Clip'), ('other', 'Other')], default=list)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
