# Generated by Django 6.0.1 on 2026-01-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheaterreports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheaterpost',
            name='suspected_hack_types',
            field=models.JSONField(default=list),
        ),
    ]
